apiVersion: projectcalico.org/v3
kind: NetworkPolicy
metadata:
  name: deny-all-allow-default
  namespace: default
spec:
  types:
  - Ingress
  ingress:
  - action: Allow
    protocol: TCP
    source:
      namespaceSelector: test-label == 'default'
